### PR TITLE
Include dropdown strings & translations

### PR DESCRIPTION
**Pull request by andylolz**
This pulls in upstream changes, and adds dropdown translations to build_translations.py (7dd1d1f & 9eb97ca)

### CODE REVIEW

**Comment by andylolz** [comment]
It sounds like tjvr is keen to include /translator in his repo, so hopefully soon it won’t be necessary to maintain the CodeClub fork (i.e. make it a mirror or a redirect instead).

**Comment by CodeClubRik** [comment]
Thanks so much Andy.

**Comment by freyjaodds** [comment]
@andylolz you are awesome!

**Comment by andylolz** [comment]
No prob! It seems to get your example right now, @freyjaodds:
http://scratchblocks.codeclub.org.uk/translator/#script=when%20this%20sprite%20clicked&from=en&to=es
Some other translations will have changed too… This is just due to Scratch updating & improving their own translations.

**Comment by CodeClubRik** [comment]
> Some other translations will have changed too… This is just due to Scratch updating & improving their own translations.

Hi @andylolz -- is there an easy way to find out what translations have changed, just because we can update the relevant projects (if any need updating) with the new translations ourselves.

**Comment by andylolz** [comment]
> is there an easy way to find out what translations have changed

It’s a good question. No, I’m afraid I don’t know of an easy way to do this.

Gah, it seems like it would be much better to translate scratchblocks on the fly. e.g. something like:

    ```blocks lang=es
    when green flag clicked
    ```

**Comment by freyjaodds** [comment]
That would be so amazing.

Will the tool update automatically every now and then, or do we have to raise the issue and get it done manually? I presume Scratch is always improving its translations (esp. knowing how terribly my own language is currently translated in Scratch - someone is bound to fix it at some point!)

**Comment by andylolz** [comment]
> Will the tool update automatically every now and then, or do we have to raise the issue and get it done manually?

It has to be done manually, which is not too painful… Figuring out which translations need to be updated in the markdown (the bit Rik mentioned) is unfortunately quite painful.

> esp. knowing how terribly my own language is currently translated in Scratch - someone is bound to fix it at some point!

You can actually do that yourself just here:
http://translate.scratch.mit.edu/is/
(you have to register for an account first)

**Comment by freyjaodds** [comment]
​Thanks Andy - Was just wondering what would be the best process for it,
should I raise an issue on github, say every three months or so to make
sure the tool is up to date?

And yes, I'll see if I can find time to contribute to the terrible
Icelandic translations, cheers :)​

*Freyja Oddsdóttir*
Operations Executive
www.codeclubworld.org
@CodeClubWorld <http://twitter.com/codeclubworld>  |
www.facebook.com/codeclubworld <http://facebook.com/codeclubworld>

**Pull request merged**
